export enum GameSprite {
  turtle = 'turtle',
  turtleEmerging = 'turtleEmerging',
  turtleSink = 'turtleSink',
  lillyPad = 'lillyPad',
  fly = 'fly',
  grass = 'grass',
  river = 'river',
  road = 'road',
  winBad = 'winBad',
  winGood = 'winGood',
  logLg = 'logLg',
  logSm = 'logSm',
  die = 'die',
  carFire = 'carFire',
  carSemi = 'carSemi',
  carBlue = 'carBlue',
  carGreen = 'carGreen',
  carYellow = 'carYellow',
  frog = 'frog',
  alligatorBody = 'alligatorBody',
  alligatorHead = 'alligatorHead',
  guts = 'guts',
  fire = 'fire',
}
